id: IAA6EA6B7
legacy_id: P009612
ocr_import_info:
  bdrc_scan_id: W00KG03984
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T20:37:46'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T13:40:07.480519+00:00'
last_modified: 2022-08-30 21:40:27.311359
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00KG03984
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW00KG03984
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཀཿཐོག་རྒྱུད་སྡེ་བཤད་སྒྲུབ་ནོར་བུ་ལྷུན་པོའི་སྣང་བརྙན།
statistics:
  ocr_word_mean_confidence_index: 0.5870225948415729
  ocr_word_median_confidence_index: 0.5400000214576721
quality: null
bases:
  I00KG03987:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03987
      total_pages: 171
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00KG03987.txt
    statistics:
      ocr_word_median_confidence_index: 0.5400000214576721
      ocr_word_mean_confidence_index: 0.5870225948415729
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
