id: IAA6EA6B7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T20:38:52+00:00'
last_modified: '2022-06-08T12:15:47.411968+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG03984
  title: ཀཿཐོག་རྒྱུད་སྡེ་བཤད་སྒྲུབ་ནོར་བུ་ལྷུན་པོའི་སྣང་བརྙན་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '6215':
      image_group_id: I00KG03987
      title: ''
      total_pages: 171
      order: 1
      base_file: 6215.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
