id: P009612
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-19 20:40:44.144413
source_metadata:
  id: bdr:W00KG03984
  title: ཀཿཐོག་རྒྱུད་སྡེ་བཤད་སྒྲུབ་ནོར་བུ་ལྷུན་པོའི་སྣང་བརྙན་
  author: ''
  volumes:
    7b454154772f4c91adc84b5be56da357:
      image_group_id: I00KG03987
      title: ''
      volume_number: 1
      total_pages: 171
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
