id: P009612
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG03984
  title: ཀཿཐོག་རྒྱུད་སྡེ་བཤད་སྒྲུབ་ནོར་བུ་ལྷུན་པོའི་སྣང་བརྙན་
  author: ''
  volumes:
    7b454154772f4c91adc84b5be56da357:
      image_group_id: I00KG03987
      title: ''
      volume_number: 1
      total_pages: 171
